holland_mysqldump.py

A few fixes based on previous feedback:
* Ensure output of `mysqladmin status` goes to `/dev/null`
* Don't do `.split()` on `None` value
* Look in `/etc/holland/backupsets/default.conf` for credentials before `mysqldump.conf`, as this is where dedicated support teams often configure things and that location takes precedence.
The first two of these have been used in lamp builds for a while now.  The third one is new.

Holland Plugin Fixes

---

inodes.py

Takes arguments:
:arg: directory - Which directory to run statvfs on. Will run like
`df`, where it gets the information for the filesystem containing
the directory.
Returns:
```
status ok success
metric inodes_percent float 0.000151 percent
metric inodes_total uint64 976761536 inodes
metric inodes_avail uint64 976613949 inodes
```
Or will return:
```
status err Failed to check status of inodes
```

Add inode check

---

docker_stats_check.py

Docker came up with the stats API in their 1.5 release.  (https://docs.docker.com/reference/api/docker_remote_api_v1.17/#get-container-stats-based-on-resource-usage)
This PR aims to provide a plugin for the agent so that we can start piping container level stats to our monitoring system. This will allow someone to have complete visibility into their systems even if containers are first class citizens of their infrastructure.
These are the possible stats that we can include in this plugin: https://gist.github.com/ynachiket/67a9dac9293fe55643be. As of now I have chosen the 10 stats that I feel are valuable. Please suggest what you would like to be included instead.

Docker container level stats through docker stats api

---

open_files.py

This adds a plugin to track open file handles on Linux using the information in `/proc/sys/fs/file-nr`.

Add plugin to track file handles on Linux

---

chef_node_checkin.py

It can be argued that the intent of the plugin is about clients that haven't converged and shorting out because the log is empty violates this.  However, generating alerts for logs that recently rotated just cries wolf too often to be of use.

chef_node_checkin: short out when log is empty

---

dns_resolution.sh

This is a fork of #53 that fixes some logic issues and address the requested feature.
```shell
./dns_resolution.sh rackspace.com AAAA
status ok dns_lookup successful
metric dns_lookup string successful
```
```shell
./dns_resolution.sh rackspace.org
status ok dns_lookup successful
metric dns_lookup string successful
```

dns resolver

---

holland_mysqldump.py

This should fix issues #90, #91, and #92:
#90:  This adds back in the "host" configuration that was removed when #85 was reverted.
#91: As that issue states, the priority of the checks should be with the credentials in the backupsets configuration files rather than the defaults-extra-files, so the if, elif is switched to check with the credentials found in the holland configuration files rather than use the MySQL defaults-extra-files.
#92: This is the major change here.  With Holland having the ability to have multiple backupsets configured at the same time, the check needs to read the holland configuration for the backupsets to check rather than defaulting to a fixed "default".  This logic changes the single backupset check to a list read from the holland configuration and then iterates …

Holland MySQLdump check 

---

memcached_stats.py

Previous iteration caused "fill_percent" to always return zero, due to rounding

small bug fix for "fill_percent"

---

onmetal_v1_smart.py

This emits one metric; % of rated PE cycles the node has been subjected
to. This is a leading indicator of failure. Returned as a percentage
because max pe cycles can vary per SATADOM model.

Adding disk life check for OnMetal v1 SATADOMs.

---

onmetal_v1_smart.py

The _fail() method should stop all execution of the script; this change
fixes the bug where it doesn't.

Make _fail() exit after printing

---

docker_stats_check.py

The plugin used an api which streams container metrics. This made the plugin never "finish" and hence time out.
This will fix that.

exit after a snapshot

---

ntp_offset.sh

This changes the plugin so that it:
- computes correct average values,
- emits the number of current active time sources as a metric,
- exits with 1 if the average offset can't be computed for any reason

rework ntp_offset.sh

---

nfs-status.sh

Simple plugin that takes a host and a directory as an argument, and makes sure that the specified host is serving the specified directory to this client. In this way, you can check for the NFS master being down, bad networking, a changed configuration (i.e. missing export), etc.

Adds NFS monitoring plugin

---

galera.py

Adds a plugin that obtains various `wsrep_` related stats from MySQL for use in monitoring a Galera cluster node.  Must add a `[raxmon]` group to an existing or new MySQL options file.  The `[raxmon]` group should contain at least the user and password used to connect to MySQL.  Defaults to `/root/.raxmon.cnf`, or you can use the `-f` options to specify a path.

add galera plugin

---

content_check.py

Rackspace Monitoring plugin to check a URL for a regular expression.  Useful if the URL you need to check is not publicly accessible, but can be reached by another entity.  Returns the metric 'found' with a value of 'yes' or 'no'.
Tested on Python 2.6, 2.7, and 3.5.

add content_check plugin

---

long_process.sh

We had some cron jobs that were getting stuck and nothing to notify us this was happening. This script checks the run time of a process in minutes and reports back the number of long processes and their PIDs.

feat(long_process): Monitor long running processes

---

varnish4.sh

Creates a Varnish 4 version of the plugin.  Includes variables for the cache_hit and cache_miss metric names, and updates the formula used to calculate hit_rate to include only cache hits and misses.

feat(varnish4): add varnish4 plugin

---

port_check.sh

Services such as MySQL have an output that interrupts the status of this alarm. The if/then conditional is the main part of the script that Cloud Monitoring needs to read to function.

redirect all output from nc command to remove the chance of false alarm

---

chef_node_checkin.py

- refactored to stop using regular expressions. This results in a x 3
speedup in my testing.
- removed time module as it is unused
- removed timedelta as it is unused
- removed 'response' array, as it is instantiated, but unused

refactored chef_node_checkin.py to remove unneeded modules

---

holland_mysqldump.py

Python 2.4. (centos 5) doesn't provide the 'all' function.
The script now checks for it and provides it itself if the system doesn't.

Support for centos5 / python 2.4 for holland monitor

---

docker_stats_check.py

Recent Docker versions (e.g., 17.03.0) return 'networks' dict which contains per-device statistics. Old versions return 'network' dict that doesn't distinguish different devices. This patch adds support for both 'network' and 'networks' dicts; it also prints per-device stats if available.
Second patch adds support for current number of PIDs in a container.

docker_stats_check: support for several network devices returned by API "stats" call and for current number of PIDs metric

---

check-mount.sh

Adds a plugin to check that a mounted filesystem is mounted and (optionally) that a flag file exists and is readable.
Sample plugin command:
```
check-mount.sh /path/to/mount/point some_file_in_mount_point
```
Sample alarm criteria:
```
if (metric['mounted'] != 1) {
return new AlarmStatus(CRITICAL, 'The mount point is not mounted: #{path}');
}
if (metric['flag_file'] != '' && metric['flag_file_exists'] != 1) {
return new AlarmStatus(CRITICAL, 'The flag file does not exist: #{path}/#{flag_file}');
}
if (metric['flag_file'] != '' && metric['flag_file_readable'] != 1) {
return new AlarmStatus(CRITICAL, 'The flag file is not readable: #{path}/#{flag_file}');
}
return new AlarmStatus(OK, 'The mount point is OK: #{path}');
```

Add check-mount.sh to check mounted filesystems

---

check-mount.sh

This is an update to this contributed plugin that I made a week or two ago.  It was my first plugin and I didn't realize that if it returns a non zero value, Rackspace won't gather any metrics and instead gives a more generic error.
This should allow for better error messages based on the metric results.

Always return exit code 0 in check-mount.sh

---

ubuntu_updates_check.sh

Add an additional metric to `ubuntu_updates_check.sh` called `upgradable_packages`, which is a comma separated list of upgradable package names.
This uses the `apt list --upgradable` command under the hood, which is available on newer releases of Ubuntu.

Include names of upgradable packages in metrics

---

ubuntu_updates_check.sh

The Rackspace Intelligence system needs to have a string of some sort, even when there are no upgradable packages.  In cases where there are not any upgradable packages, it will now return `n/a` instead of nothing so that Rackspace Intelligence has a string metric available.

Bug fix in latest update to ubuntu_updates_check.sh

---

cloudbackup_mon.sh

The Rackspace API has been returning lots of intermittent invalid JSON responses lately causing lots of false alarms for checks that make use of the `cloudbackup_mon.sh` plugin.
This change will allow the script to retry each API call up to 5 times (defined as `$MAX_RETRIES`) before returning an error message.
A new metric variable has been added called `retry_count`, which is a count of how many retries, if any, had to be made to get valid JSON responses from the API.

Retry API requests up to 5 times before erroring

---

haproxy.rb

Removing request rate since its value can be derived from total requests. Also found the fidelity of the "rate" is not help on systems with low, near-zero rates.

Nodes with large number of haproxy backends can exceed metric limit
