windows/service_mon.ps1
Created a windows folder so its easier to see which plugins are for windows vs linux.
=> Windows service monitor.

holland_mysqldump.py
This adds the additional check for host config option in the
holland configs and the extra check for the options files
for the ping check.  This is needed when holland is
pointing to a DBaaS instance.
Also cleaned up a few "pep8" recommendations.
=> Add in check for host config for mysql ping and status check

holland_mysqldump.py
Reverts racker/rackspace-monitoring-agent-plugins-contrib#85
=> Revert "Add in check for host config for mysql ping and status check"

mongodb_stats.py
This is an update to #10 to rebase and make mergable and addresses the style comments.
> Added integration for authentication for those using a secured replica set. Also added a conditional check for indexCounters stats. Some older mongodb versions placed that data within an extra array. This keeps the script from crashing.
=> Authentication integration & ['indexCounters']['btree'] checks

holland_mysqldump.py
=> [rebased] Added read the --defaults-file to check_ping()

onmetal_v1_smart.py
- Add alternate spacing of Fastable SATADOM model
- Add semicolons for alarm criteria.
=> Fix two minor issues in onmetal monitoring script

.gitmodules
Wait for the readme pull to land
https://github.com/creationix/gardener/pull/1
Edit: It landed, merging.
=> feat(contrib/gardener): Port over tims gardener plugin

mysql_ping.py
Subject says it all, a simple commit to document how to use the plugin.
=> Document how to use mysql_ping.py plugin

memcached_stats.py
=> Document a minimal alarm criteria for memcached_stats.py

php-fpm_status_check.sh
php-fpm plugin, tested on centos6 and ubuntu 14.04
=> add php-fpm plugin

cloudbackup_mon.sh
The script wasn't working due to changes made in our APi a while back.
Now it works, but it needs a new param 'datacenter'.
=> Updated cloudbackup_mon.sh to work with latest Rackspace API

check_openmanage.sh
Hopefully other folks will find this useful.  I'm piggybacking on an existing Nagios script, but the output format between Nagios and Rackspace Monitoring is similar enough, this was fairly straightforward to implement.
=> add check_openmanage.sh plugin

README.md, ping.sh, windows/ping.ps1
Now with min, max, average and even packet loss metrics
=> ICMP PING plugins for Linux and Windows

check_openmanage.sh
I wanted to make this more generic and not hard code anything, making use instead of the args attribute via the API.  This change will allow that.
=> update OMSA wrapper to use API arguments

ping.sh, windows/ping.ps1
implements attributes to configure the number of pings per check and the interval between them (defaults to 5 pings with 2 second intervals)
these defaults would be the same as they are in the vanilla (external) Ping checks currently
=> ping scripts act more like ping checks (1 ping / 2 seconds)

dir_stats.sh
via https://github.com/racker/chef/pull/2246 a plugin we've used on the MAAS timed for years
=> dir_stats.sh

check_nodering.py
Adding new check nodering script.
=> Adding check nodering script

check_nodering.py
=> Updating cassandra check to output metrics

uptime_reset_detector.sh
Simple script to detect uptime resets
=> Added uptime reset detector script for Linux

cloudbackup_mon.sh
Changes:
- Updated the Rackspace Monitoring Alarm example criteria so that it shows a brief diagnostic summary if there was a backup error.
- Monitoring checks were flapping due to the JSON data not being properly parsed with grep. Used python to read data instead.
- Fixed the logic so that it shows the Cloud Backup Report of a given BackupConfigurationId (third parameter).
- Force user to specify a BackupConfigurationId parameter if multiple Backup Configurations were detected.
- Set default values for the output metric variables if the corresponding variables didn't have data. Fixes alerts being triggered due to an unexpected empty variable.
=> Updated cloudbackup_mon.sh logic to better parse python because grepping failed

cloudbackup_mon.sh
Add start_time and age metrics to `cloudbackup_mon.sh`
=>  Add start_time and age metrics to cloudbackup_mon.sh

haproxy.rb
MAAS has a slightly forked version of the haproxy script in this repo. Notably, it comments out the last metric to avoid passing `>30` metrics
* lint
* comment out final metric due to volume limits
=> sync with maas version
